### ISSUE TITLE
Crash when deleting entire space platform

### ISSUE THREAD

**Issue by Lykam** [RedRafe/factory-efficiency-tracker#1]
Steps to recreate:
Map to space platform
Delete the entire thing with decon. 
Near the last few items of the platform this happens.

The mod Factory Efficiency Tracker (2.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-efficiency-tracker::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__factory-efficiency-tracker__/scripts/stats.lua:54: in function 'update_stats'
	__factory-efficiency-tracker__/scripts/stats.lua:103: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
	
		
	
[_autosave3.zip](https://github.com/user-attachments/files/17816461/_autosave3.zip)

![image](https://github.com/user-attachments/assets/9478e877-7c2d-443e-ad4b-461916f1c578)

**Comment by RedRafe** [comment]
Thanks, fixed with new release
